version: 2.1
jobs:
  node:
    working_directory: ~/linkmood
    docker:
      - image: cimg/node:12.16

    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: npm install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: ~/linkmood
          paths:
            - node_modules

  android-build-and-test:
    working_directory: ~/linkmood/android
    docker:
      - image: circleci/android:api-29-node
    steps:
      - checkout:
          path: ~/linkmood

      - attach_workspace:
          at: ~/linkmood

      # - restore_cache:
      #     key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}

      # - run: bundle install

      # - save_cache:
      #     key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
      #     paths:
      #       - vendor/bundle

      - run: ./gradlew app:assembleRelease
      # - run:
      #     name: fastlane tests
      #     command: |
      #       mkdir -p test-results/fastlane
      #       bundle exec fastlane test
      #       mv fastlane/report.xml test-results/fastlane

      # - store_test_results:
      #     path: test-results

      # - store_artifacts:
      #     path: test-results

workflows:
  node-android-ios:
    jobs:
      - node
      - android-build-and-test:
          requires:
            - node
      # - macos-build-and-test:
      #     requires:
      #       - node
            
